name: intro-rabbitmq

services:
  mq:
    image: rabbitmq:3-management-alpine
    # volumes:
    #   - type: bind
    #     source: ./config/rabbitmq.config
    #     target: /etc/rabbitmq/rabbitmq.config
    ports:
      - target: 15672
        published: 8080
        protocol: tcp
        mode: host
    healthcheck:
      test: ["CMD", "rabbitmqctl", "status"]
      interval: 5s
      timeout: 10s
      retries: 5
      start_period: 20s
  
  producer:
    build:
      context: producer/
    depends_on:
      mq:
        condition: service_healthy

  consumer:
    build:
      context: consumer/
    depends_on:
      mq:
        condition: service_healthy
        
